# Generated by Django 3.0.1 on 2020-03-15 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AuthorImage', models.CharField(default='http://quoteslab.net/contents/uploads/bill-cameron-mystery-author-400x400.jpg', max_length=250)),
                ('AuthorName', models.CharField(max_length=80)),
                ('AuthorEmail', models.EmailField(max_length=254)),
                ('AuthorDesc', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=80)),
                ('CategoryImage', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Message', models.CharField(max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PublicationImage', models.CharField(max_length=250)),
                ('PublicationName', models.CharField(max_length=80)),
                ('PublicationDesc', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookImage', models.CharField(default='http://www.macedonrangeshalls.com.au/wp-content/uploads/2017/10/image-not-found.png', max_length=5000)),
                ('BookName', models.CharField(max_length=50)),
                ('BookDesc', models.CharField(max_length=500)),
                ('BookPrice', models.IntegerField()),
                ('BookStock', models.IntegerField()),
                ('SubCategory', models.CharField(default='NULL', max_length=150)),
                ('Author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='MainIndex.Author')),
                ('Category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='MainIndex.Category')),
                ('Publication', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='MainIndex.Publication')),
            ],
        ),
    ]
