# Generated by Django 3.0.1 on 2020-03-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=100)),
                ('CustomerEmail', models.EmailField(default='abc@gmail.com', max_length=100)),
                ('CustomerPassword', models.CharField(max_length=100)),
                ('CustomerAddress', models.CharField(default='Berkly street', max_length=250)),
                ('CustomerAddress2', models.CharField(default='No Other Optional Address', max_length=250)),
                ('CustomerPinCode', models.IntegerField(default='360005')),
                ('BillingFirstName', models.CharField(default='No Billing First Name ', max_length=100)),
                ('BillingLastName', models.CharField(default='No Billing Last Name ', max_length=100)),
                ('CustomerState', models.CharField(default='Gujarat', max_length=100)),
                ('CustomerCity', models.CharField(default='Rajkot', max_length=100)),
            ],
        ),
    ]
