# Generated by Django 3.0.1 on 2020-03-15 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MainIndex', '0001_initial'),
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MainIndex.Book')),
                ('user', models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='Registration.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderitems', models.ManyToManyField(to='Cart.Cart')),
                ('user', models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='Registration.Customer')),
            ],
        ),
    ]
